### ISSUE TITLE
Star Pattern Programs in CPP

### ISSUE THREAD

**Issue by shivanithorve01** [msameerfarooq/Hacktoberfest2022#207]
I want to add following star patterns in separate Star Patterns Folder : 

1. Half Pyramid
2. Inverted Half Pyramid 
3. Cross Half Pyramid
4. Inverted Cross Half Pyramid
5. Hollow Triangular Pyramid

@msameerfarooq Please assign me this issue.

**Comment by Hiresh007** [comment]
please assign

**Comment by msameerfarooq** [comment]
Go Ahead! Your contributions will be welcomed!

**Comment by Hiresh007** [comment]
added the codes

**Comment by Hiresh007** [comment]
please put hacktoberfest tag

**Comment by Hiresh007** [comment]
check the pr

**Comment by Hiresh007** [comment]
please add hacktoberfest  accepted tag
