### ISSUE TITLE
I would like to add code of binary search tree in CPP.

### ISSUE THREAD

**Issue by Abhishek-Nag29** [msameerfarooq/Hacktoberfest2022#232]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Abhishek-Nag29** [comment]
I would like to add code for binary search tree in CPP.

**Comment by msameerfarooq** [comment]
assigned

**Comment by Ak8933** [comment]
hey @msameerfarooq  please assign this issue to me?
