### ISSUE TITLE
Wanna add classical N queens problem concept in the recursion section

### ISSUE THREAD

**Issue by Kavya2719** [msameerfarooq/Hacktoberfest2022#254]
Hello @msameerfarooq
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other and we have to find total number of different ways we can do this.

This is a nice and important classical concept for beginners while learning recursion. May you please assign me to contribute this into your repo.

**Comment by msameerfarooq** [comment]
Assigned!

**Comment by Kavya2719** [comment]
Thanks, I have maded the PR, do check it out and let me know if there are any changes or improvements to be made @msameerfarooq , Happy to contribute
